### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
Starter package for Fastlane, see #4

* be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this
* for formatting of the `full_description.txt`, you can find some hints [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane)
* you can move your screenshots (which are currently in `Play-assets`) to the proper location inside `fastlane/metadata/android/<locale>/images` (replacing `<locale> by `en-US` and `de` accordingly, I see you have screenshots for both; see the cheat sheet for which sizes should go to which directory – I guess Pixel-C would be `tenInchScreenshots`, for example, and I'd place the Pixel-3 into `phoneScreenshots` so there are some "default ones" :wink:)

If there are any questions, just ask :smiley: I gladly cross-check once you think you've got everything in.

### CODE REVIEW

**Review by 1fish2 — APPROVED** [review]
This is great. Thank you!

Soon I'll move in the screenshots and a recent edit to `*/full_description.txt`. Will IzzyDroid automatically notice those updates when there isn't a new app version?

**Comment by IzzySoft** [comment]
> Will IzzyDroid automatically notice those updates when there isn't a new app version?

No, only when there's a new version. But if you let me know I can trigger a manual pull. Please definitely let me know once you've added screenshots so I can check to enable them, too (I do that manually for optimization – always trying to find the best balance between size and quality in some cases means converting from PNG to JPG and in others to avoid that). I just "activated" what's there now. When updating `full_description.txt` please pay attention to the notes [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) so it renders fine (else it might break formatting). Other than F-Droid (and Play), my engine tries to render it as Markdown if possible, looks much better (especially when it comes t lists) :smile:

**Comment by IzzySoft** [comment]
Ah, PS: If you wonder about the Mix of HTML in the description, that's for compatibility – neither F-Droid nor Play do work with Markdown in descriptions (they both use plain text with some minimal HTML tags allowed). So the format-mix I choose works well with them and great with my repo :smile:

**Comment by 1fish2** [comment]
OK. I copied in minor text updates to `full_description.txt` and converted the screenshots to jpg files at the sizes used on https://apt.izzysoft.de/fdroid/index/apk/com.onefishtwo.bbqtimer

Long term, does it work to unify the full descriptions between fastlane & Play, using nested Markdown bullets?

**Comment by IzzySoft** [comment]
Thanks! Update looks good. Adjusted the config here accordingly. Just a note on screenshots: should you ever want to apply for inclusion with F-Droid, keep in mind there's currently a bug in the Fastlane implementation with them making it impossible to **delete** screenshots. Wok around is to **overwrite** them. Fo that, a naming like `01.jpg`, `02.jpg` etc. is probably better.

As for nested bullet-point lists: to my knowledge, that's a problem. While with F-Droid you could use HTML, they always replace line-breaks by `<br>` (so you'd have to put the entire list on a single line or it would look weird – which in turn would make it hard to maintain). Play Store to my knowledge doesn't support that at all – unless you use weird formatting with "unbreakable spaces" (as you have it there currently), which then looks ugly on small screens where the text needs to be wrapped. I've no idea how Play would deal with HTML input.

So if you insist on using the same for all 3 places, that would mean using "ugly ASCII". My setup supports that as well (I can set it to act the same way as F-Droid in this concern), but I'd only use that as last resort as it really does not look nice.

**Comment by 1fish2** [comment]
If I rename those screenshots to `01.jpg` et al now, would that make extra work for you?

I recall iterating with Play Store description formatting years ago, but now we have to wait on review approval for each update. Is there a way to test formatting for Play, IzzySoft, and F-Droid? I can keep these files in sync semi-manually and maybe write a Python script.

**Comment by IzzySoft** [comment]
> If I rename those screenshots to `01.jpg` et al now, would that make extra work for you?

Not at all. The mentioned bug does not exist in my repo (I use different mechanisms to maintain Fastlane).

> Is there a way to test formatting for Play, IzzySoft, and F-Droid?

I've no idea about Play. For my repo, I can test with my local instance (not the public one) and restore afterwards if needed. For F-Droid, not really unless you set up a copy of fdroidserver for yourself and use that for the entire workflow – but coming close, my local instance again could be "abused" if I just reconfigure to simulate F-Droid's parsing (i.e. taking the file as-is and just replacing each line break by `<br>`).

But still, that would be quite some work as I'd also have to run the conversion manually then (the automated workflow pulls fastlane from the app's repo). Could be achieved with a temp Github repo just holding the fastlane data, setting up a load of "fake languages" holding different formattings of the same description, and then running twice (once as Markdown for mine, then as plain text to simulate F-Droid). But who shall investigate then? My local instance is not publicly available.

**Pull request merged**
